<?php

/**
 * Adds a "404" menu item under the "Templates" submenu in the main navigation.
 * 
 */
add_filter( 'render_block_core/navigation', function ( $block_content, $block ) {
    if ( empty( $block["attrs"]["className"] ) || $block["attrs"]["className"] !== 'main-navigation' ) {
        return $block_content;
    }

    // Check if the "404" item already exists in the navigation
    if ( strpos( $block_content, 'menu-item-404' ) !== false ) {
        return $block_content;
    }

    // Initialize DOMDocument and DOMXPath.
    $doc = new DOMDocument();

    // Suppress warnings generated by loadHTML.
    libxml_use_internal_errors( true );
    @$doc->loadHTML('<?xml encoding="utf-8" ?>' . $block_content );
    $xpath = new DOMXPath( $doc );

    // Find the "Templates" menu item.
    $templates_item = $xpath->query( "//li[contains(@class, 'wp-block-navigation-item')]//a[normalize-space(text())='Templates']/ancestor::li[1]")->item( 0 );

    if ( $templates_item ) {
        // Find or create the submenu under "Templates".
        $submenu = $xpath->query( ".//ul[contains(@class, 'wp-block-navigation__submenu-container')]", $templates_item )->item( 0 );
        if ( ! $submenu ) {
            return $block_content; // No submenu found, return original content.
        }

        // Verify if the "404" item already exists.
        $existing = $xpath->query( ".//a[contains(@href, '/404')]", $submenu );
       
        if ( 0 === $existing->length ) {
            $new_item = $doc->createElement( 'li' );
            $new_item->setAttribute( 'class', 'wp-block-navigation-item menu-item-404');

            $link = $doc->createElement( 'a', '404' );
            $link->setAttribute( 'class', 'wp-block-navigation-item__content' );
            $link->setAttribute( 'href', esc_url( home_url('/404') ) );

            $new_item->appendChild( $link );
            $submenu->appendChild( $new_item );
        }

        $block_content = $doc->saveHTML( $doc->documentElement );
    }

    return $block_content;
}, 10, 2 );
